apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-yvjr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/eozkan-tenant/partner-catalog-1/partner-catalog-yvjr@sha256:f054147a8415afa2f1b85b8e73385837a6780f1ad6e83a52f461277d15f53478
        name: my-java-springboot
        resources: {}
status: {}
